### ISSUE TITLE
Error in error correction step

### ISSUE THREAD

**Issue by jzehr** [stephenshank/convex-qsr#2]
First step of README

``` ...done!
Performing multiple testing correction...
Traceback (most recent call last):
  File "/Users/jordanzehr/anaconda3/envs/qsr/bin/cqsr_ec", line 11, in <module>
    load_entry_point('convex-qsr==0.1.0', 'console_scripts', 'cqsr_ec')()
  File "/Users/jordanzehr/anaconda3/envs/qsr/lib/python3.6/site-packages/convex_qsr/cli.py", line 77, in error_correction
    args.bam, corrected, json, fasta, end_correction=args.end_correction
  File "/Users/jordanzehr/anaconda3/envs/qsr/lib/python3.6/site-packages/convex_qsr/io.py", line 22, in error_correction_io
    error_correction.write_corrected_reads(output_bam)
  File "/Users/jordanzehr/anaconda3/envs/qsr/lib/python3.6/site-packages/convex_qsr/error_correction.py", line 339, in write_corrected_reads
    for read in self.corrected_reads(end_correction=end_correction):
  File "/Users/jordanzehr/anaconda3/envs/qsr/lib/python3.6/site-packages/convex_qsr/error_correction.py", line 287, in corrected_reads
    covarying_sites = self.multiple_testing_correction()
  File "/Users/jordanzehr/anaconda3/envs/qsr/lib/python3.6/site-packages/convex_qsr/error_correction.py", line 206, in multiple_testing_correction
    after_head_correction = covarying_sites > self.end_correction
TypeError: '>' not supported between instances of 'int' and 'NoneType' ```

**Comment by stephenshank** [comment]
Fixed in [v0.1.1](https://github.com/stephenshank/convex-qsr/releases/tag/v0.1.1). Thanks for reporting!
